export default{
    bnsp:{
        description : "Daftar unit kopetensi ",
        data : [
            {
                id:1,
                kode:"",
                unit:""
            },
            {
                id:2,
                kode:"",
                unit:""
            },
            {
                id:3,
                kode:"",
                unit:""
            },
            {
                id:4,
                kode:"",
                unit:""
            },
            {
                id:5,
                kode:"",
                unit:""
            },
            {
                id:6,
                kode:"",
                unit:""
            },
            {
                id:7,
                kode:"",
                unit:""
            },
            {
                id:8,
                kode:"",
                unit:""
            },
            {
                id:9,
                kode:"",
                unit:""
            }           
            
        ]
        },
        toefl:{
            description:"",
            data:[
                {
                    id:1,
                    kode:"",
                    unit:""
                },
                {
                    id:2,
                    kode:"",
                    unit:""
                },
                {
                    id:3,
                    kode:"",
                    unit:""
                }
            ]
        }
    }
